import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0f0d08',
  '--slot4-page-text': '#ECE7D1',
  '--slot4-panel-bg': '#1c1912',
  '--slot4-surface-bg': '#221e14',
  '--slot4-muted-text': '#8E977D',
  '--slot4-soft-muted-text': '#6b7560',
  '--slot4-accent': '#8A7650',
  '--slot4-accent-fill': '#8A7650',
  '--slot4-accent-soft': 'rgba(138, 118, 80, 0.14)',
  '--slot4-on-accent': '#ECE7D1',
  '--slot4-dark-bg': '#080705',
  '--slot4-dark-text': '#ECE7D1',
  '--slot4-media-bg': '#2a2218',
  '--slot4-cream': '#ECE7D1',
  '--slot4-warm': '#1c1912',
  '--slot4-lavender': '#221e14',
  '--slot4-gray': '#1c1912',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0f0d08',
  '--editable-page-text': '#ECE7D1',
  '--editable-container': '1400px',
  '--editable-border': 'rgba(219, 206, 165, 0.10)',
  '--editable-nav-bg': '#080704',
  '--editable-nav-text': '#ECE7D1',
  '--editable-nav-active': '#8A7650',
  '--editable-nav-active-text': '#ECE7D1',
  '--editable-cta-bg': '#8A7650',
  '--editable-cta-text': '#ECE7D1',
  '--editable-search-bg': '#1c1912',
  '--editable-footer-bg': '#080704',
  '--editable-footer-text': '#8E977D',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_4px_rgba(0,0,0,0.32)]',
  shadowStrong: 'shadow-[0_8px_32px_rgba(0,0,0,0.48)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.82))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[300px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-bold leading-[1.08] tracking-[-0.02em] sm:text-5xl lg:text-[3.25rem]',
    sectionTitle: 'text-3xl font-bold tracking-[-0.02em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] shadow-[0_2px_12px_rgba(0,0,0,0.28)]`,
    soft: `rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-panel-bg)]`,
    dark: `rounded-xl bg-[var(--slot4-dark-bg)] text-[var(--slot4-dark-text)] shadow-[0_8px_40px_rgba(0,0,0,0.5)]`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-110 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-lg border border-[var(--editable-border)] bg-transparent px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-110 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl bg-[var(--slot4-media-bg)]`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_12px_40px_rgba(138,118,80,0.18)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
